name: Compilar Plugin SUPRX
on: 
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest 
    
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4
        
      - name: Compilar com CMake
        run: |
          mkdir build
          cd build
          # A MÁGICA AQUI: Avisando o CMake para usar as ferramentas do PS Vita!
          cmake -DCMAKE_TOOLCHAIN_FILE="$VITASDK/share/vita.toolchain.cmake" ..
          make
          
      - name: Salvar o .suprx gerado
        uses: actions/upload-artifact@v4
        with:
          name: bgdl_plugin_suprx
          path: build/bgdl_plugin.suprx
